/*
 * This file is generated by jOOQ.
 */
package com.example.EvidenNewsAggregator.entities;


import com.example.EvidenNewsAggregator.entities.tables.Articles;
import com.example.EvidenNewsAggregator.entities.tables.Categories;
import com.example.EvidenNewsAggregator.entities.tables.Roles;
import com.example.EvidenNewsAggregator.entities.tables.Users;


/**
 * Convenience access to all tables in evidennewsaggregator.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>evidennewsaggregator.articles</code>.
     */
    public static final Articles ARTICLES = Articles.ARTICLES;

    /**
     * The table <code>evidennewsaggregator.categories</code>.
     */
    public static final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>evidennewsaggregator.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>evidennewsaggregator.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
