/*
 * This file is generated by jOOQ.
 */
package com.example.EvidenNewsAggregator.entities.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Categories implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer categoryId;
    private String  name;

    public Categories() {}

    public Categories(Categories value) {
        this.categoryId = value.categoryId;
        this.name = value.name;
    }

    public Categories(
        Integer categoryId,
        String  name
    ) {
        this.categoryId = categoryId;
        this.name = name;
    }

    /**
     * Getter for <code>evidennewsaggregator.categories.category_id</code>.
     */
    public Integer getCategoryId() {
        return this.categoryId;
    }

    /**
     * Setter for <code>evidennewsaggregator.categories.category_id</code>.
     */
    public Categories setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
        return this;
    }

    /**
     * Getter for <code>evidennewsaggregator.categories.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>evidennewsaggregator.categories.name</code>.
     */
    public Categories setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Categories other = (Categories) obj;
        if (categoryId == null) {
            if (other.categoryId != null)
                return false;
        }
        else if (!categoryId.equals(other.categoryId))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.categoryId == null) ? 0 : this.categoryId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Categories (");

        sb.append(categoryId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
